del *.kf
del *.kfinfo
del *.kfm
del FlamingoGreater_Adult_F_*.nif
del FlamingoGreater_Young_F_*.nif
del FlamingoGreater_Adult_M_*.nif
del FlamingoGreater_Adult_F.bf
del FlamingoGreater_Young_F.bf
del FlamingoGreater_Adult_M.bf
